.github/workflows/commit.yaml
pom.xml

Relates to: https://github.com/assertj/assertj-core/issues/2573

Force JavaDoc to only run on JDK17

---

.github/workflows/build.yml

Update CI build order

---

.github/workflows/build.yml
scripts/prepare-test-outputs-for-merge.sh

Add MacOS to list of build runners.

Run CI on MacOS

---

.github/workflows/build.yml

I've seen several cases recently where various issues like 503s from javadoc.io and connection resets from Maven  central have caused builds to fail.
This should hopefully assist in avoiding this.

Enable retrying CI steps

---

acceptance-tests/acceptance-tests-manifold-systems/pom.xml
acceptance-tests/acceptance-tests-manifold-systems/src/test/groovy/io/github/ascopes/acceptancetests/manifold/ManifoldPreprocessorTest.groovy

Now that https://github.com/manifold-systems/manifold/issues/399 has been fixed, this test should pass

Enable manifold warning preprocessor test

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/AbstractJctCompiler.java

Fixed typo at line 81 and other references of it in docs and code
#179

Fixed typo 

---

.github/workflows/main.yml

Made changes to [the main YML pipeline](https://github.com/ascopes/java-compiler-testing/blob/main/.github/workflows/main.yml#L151) to enable CI to run on macos-12 on java 19 and windows-2022 on java 19.

[Fixes #194] Made changes to the main YML pipeline

---

acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-inject/src/test/groovy/io/github/ascopes/jct/acceptancetests/avajeinject/AvajeInjectTest.groovy
acceptance-tests/acceptance-tests-avaje-inject/src/test/resources/code/module-info.java
acceptance-tests/acceptance-tests-avaje-inject/src/test/resources/code/org/example/CoffeeMaker.java
acceptance-tests/acceptance-tests-avaje-inject/src/test/resources/code/org/example/Grinder.java
acceptance-tests/acceptance-tests-avaje-inject/src/test/resources/code/org/example/Pump.java
acceptance-tests/acceptance-tests-avaje-inject/src/test/resources/junit-platform.properties
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-error-prone/src/test/groovy/io/github/ascopes/jct/acceptancetests/errorprone/ErrorProneTest.groovy
acceptance-tests/acceptance-tests-error-prone/src/test/resources/code/nullness/happy/HappyCase.java
acceptance-tests/acceptance-tests-error-prone/src/test/resources/code/nullness/sad/SadCase.java
acceptance-tests/acceptance-tests-error-prone/src/test/resources/junit-platform.properties
acceptance-tests/acceptance-tests-manifold-systems/src/test/resources/code/nullness/happy/HappyCase.java
acceptance-tests/acceptance-tests-manifold-systems/src/test/resources/code/nullness/sad/SadCase.java
acceptance-tests/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java

Contributes to #200 to add more acceptance tests.
This currently adds:
- Google Error Prone
- Avaje Inject

Add more acceptance tests

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/compliance.yml
.github/workflows/deploy.yml
.github/workflows/mutation-global.yml
acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-manifold-systems/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
codecov.yml
java-compiler-testing/pom.xml
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/DoNotMutationTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicLegacyCompilationIntegrationTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicModuleCompilationIntegrationTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicMultiModuleCompilationIntegrationTest.java
pom.xml
scripts/prepare-test-outputs-for-merge.sh

- Use surefire for unit tests in main module.
- Use failsafe for integration tests in main module.
- Use separate JaCoCo report for unit tests.
- Use separate JaCoCo report for integration tests.
- Rework mutation test skippage annotation in main module.
- Instruct JaCoCo to run on verify phase as well as test phase.
- Implement codecov feature flags for integration and unit tests individually.
- Skip running test runner at all for Manifold when on `<jdk>(11,)</jdk>` similar to what Spring does for `<jdk>[,15)</jdk>`
- Rewrite parts of `prepare-test-outputs-for-merge.sh` to cope with new report locations.
Closes #122.

Closes #122 - split up unit and integration test runners and coverage

---

java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/LazyTest.java

Closes #220; will reopen if the issue appears again.

Make LazyTest stricter to detect and avoid flakes

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/PathFileObject.java

Tidy up PathFileObject class

---

.github/jvm.config
.github/workflows/deploy.yml
.gitignore
acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-manifold-systems/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
java-compiler-testing/pom.xml
pom.xml
scripts/common.sh

Closes #16 - makes the first release and implements the pipelines for Maven central releases.

First public release (non-stable) to get pipelines working.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/AbstractCompilersProvider.java

Add documentation to the provider to show users how to extend the API.

Add documentation to AbstractCompilersProvider

---

.github/workflows/deploy.yml
acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-manifold-systems/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
java-compiler-testing/pom.xml
pom.xml

Do not use the Nexus plugin for releases, as there is no nice way of satisfying all of these constraints due to how the plugin works:
- Update ALL version numbers correctly
- Do not attempt to deploy acceptance tests
- Do not fail because acceptance tests do not contain artifacts in the main sources
- Automatically close the release on Nexus to deploy it.

Do not use Nexus plugin

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/deploy.yml
README.md
scripts/common.sh
scripts/prepare-test-outputs-for-merge.sh

GitHub does not compress the build report files until the build ends.
This means that the operation of stashing reports from each platform
and then unstashing them later for bulk processing in the publish
reports stage takes a very long time (several minutes sometimes), since
each file has to be fetched from the object store individually. This
can be several thousand files in total due to the number of tests and
the number of runners those tests get called upon.
This change compresses these files during the build into a tarball to
reduce the number of files being requested from the object store, and
reduces the size of those files via gzip compression.

Make CI compress reports during processing to speed up builds

---

java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/JctFileManagerImplTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerImplTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/package-info.java

adds two Junit tests for JctFileManagerImpl module. Kindly consider this as my initial draft
related to #219

adds two unit tests for JctFileManagerImpl module.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctCompilerImplTest.java

Removes the -implicit flag from the default compilation settings
for Javac, as it may hide potential compilation bugs.

Remove -implicit flag from default compilation

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/CompilationMode.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctFlagBuilder.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctFlagBuilderImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctFlagBuilderImplTest.java

Adds a new option to JctCompiler that enables the user to specify the
compiler mode to run under.
By default, nothing is changed, but the user may opt to specify the
`ANNOTATION_PROCESSING_ONLY` option which will pass `-proc:only` to
Javac, or to specify `COMPILATION_ONLY` which will pass `-proc:none`
to Javac.

Add ability to only run annotation processing/only run compilation

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctJsr199Interop.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/JctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JctJsr199InteropTest.java

This enables passing classes to compile to the `.compile` method as explicit arguments,
should the user decide they want to do this.

Add ability to limit the classes that actually get compiled

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TracingDiagnosticListener.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/LoggingFileManagerProxy.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/LoomPolyfill.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/diagnostics/TraceDiagnosticTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/diagnostics/TracingDiagnosticListenerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/LoomPolyfillTest.java

This enables the use of the newer thread ID support that cannot be spoofed or overridden in the OpenJDK implementation.

Support project loom threads properly

---

.gitattributes
.github/workflows/build.yml
.github/workflows/deploy.yml
.mvn/jvm.config
.mvn/maven.config
mvnw
scripts/prepare-test-outputs-for-merge.sh

- Speed up builds by uploading one bulk report tarball rather than individual files.
- Switch out GZIP with XZ and use the maximum compression factor.

Speed up builds

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java

Prerequisite of another prerequisite!
All compiler objects will now have a name in their public API.

Add ability to customise the names of compiler objects

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/AbstractCompilersProvider.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilerTest.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilersProvider.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/VersionStrategy.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/AbstractCompilersProviderTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/JavacCompilersProviderTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/VersionStrategyTest.java

Implement ability to change default versioning strategy in JUnit support.
If the user wishes to iterate across sources/targets instead of releases for the JUnit annotations, there is now an attribute that can be overridden to support that.
This is a breaking change in the JUnit API, but since this is not yet a fully stable release,
I am leaving the versioning as-is for this change. This only affects custom compiler
implementations with custom JUnit parameters anyway. For 99.99% of use cases, this will not
affect anything.

Versioning strategies in Junit support.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilerTest.java

- Add default tags to run JCT-specific tests -- `java-compiler-testing-test` and `javac-test`. This means anyone using JCT can just run `./mvnw test -Dgroup=javac-test` if they want to run all of the javac tests but nothing else in their builds.
- Disable builds if in a GraalVM native image to prevent untested behaviour.
- Mark the JavacCompilerTest annotation as a TestTemplate to assist IDE support.

Enrich the Junit API

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctFlagBuilderFactory.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/Jsr199CompilerFactory.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctCompilerImplTest.java

Replace #getFlagBuilder and #getJsr199Compiler with factory pattern in AbstractJctCompiler class and implementations.

Use factory pattern to initialise flag and JavaCompiler objects

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ContainerGroupRepositoryImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TeeWriter.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurer.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/ModuleDiscoverer.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerImplTest.java

This splits up the file manager system into smaller components to reduce complexity of each
class.
There is now a separate repository mediator class, and module discovery is performed in a utility class in the utils package instead, enabling reuse and easier ability to swap out the existing implementation with new logic in the future, should it be needed. This also makes it easier to stub module detection in tests by using MockedStatic in Mockito

Simplify the JctFileManagerImpl class into a separate repository

---

java-compiler-testing/pom.xml

v5.0.0 of Mockito uses the inline mock maker by default so there is no need to use mockito-inline now.

Replace mockito-inline with mockito-core

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/PathFileObject.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/FileBuilderImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/PathFileObjectTest.java

- Fix some bugs in PathFileObject  
- Mark methods in PathFileObject as raising NoSuchFileException rather than FileNotFoundException
which was previously incorrect information.
- Fix bug where the 'name' of a PathFileObject could previously have been an absolute path
if the PathFileObject was initialised with an absolute file path. Now it will match the
string representation of the relative path on the object.
- Rename getRoot to the clearer 'getRootPath' which is consistent with other
method naming in this class.
- Update IllegalArgumentException that is thrown if a root path is not absolute
so that it conveys the value of the erroneous parameter in the error message.
- Implement tests for PathFileObject.
- Replace FileNotFoundException in FileBuilderImpl with NoSuchFileException …

PathFileObject tests and bugfixes

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/VersionStrategy.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/AbstractCompilersProviderTest.java

Simplify the internal implementation slightly.

Simplify VersionStrategy class

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/RamFileSystemProvider.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/DefaultFileSystemProviderImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/RamDirectoryImpl.java
java-compiler-testing/src/main/java/module-info.java

Enables easily swapping out JIMFS with another RAM file system implementation in the future
should anyone wish to do that. 
Will also make transitioning to changes w.r.t. #311 easier.

Implement SPI to allow swapping out JIMFS at runtime (part of #311)

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/AbstractPackageContainerGroup.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/OutputContainerGroupImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PackageContainerGroupImpl.java

- Declare the classloader to use in AbstractPackageContainerGroup for all implementations.
- Use anonymous classes for the internal package group implementations rather than static classes.

Simplify container group implementation code.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/OutputContainerGroup.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ContainerGroupRepositoryImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/OutputContainerGroupImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerImplTest.java

Closes #219.
- Implements file manager implementation tests
- OutputContainerGroup getFileForInput / getFileForOutput / getJavaFileForInput / getJavaFileForOutput
methods will now only consider non-module container groups. Module containers
should be inspected by calling `.getModule("module.name").getFileForInput`
instead.

File manager implementation tests, simplify OutputContainerGroup expectations

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/PathRoot.java

Fixes #323. The previous description was misleading and incorrect for the current code-base architecture.

Amend JavaDoc for PathRoot

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ContainerGroupRepositoryImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/OutputContainerGroupImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java

A bug was discovered that results in a NoSuchElementException being raised if a user attempts to register a module in an output location that was created without an initial package on a file system to place files in.
To fix this bug, a few core functionalities have changed slightly:
- JctFileManager can now throw IllegalArgumentException from createEmptyLocation(). This will be thrown if the location is an output location or a module location.
- OutputContainerGroupImpl will now raise an IllegalStateException if it detects that the container group has been misconfigured as outlined above. This error will explain how to mitigate the issue.
- ContainerGroupRepositoryImpl will now register the path root that resides behind one or more modules being registered to it. This is also covered by …

Fix bug around registering a module in an empty output location.

---

acceptance-tests/acceptance-tests-dogfood/pom.xml
acceptance-tests/acceptance-tests-dogfood/src/test/java/io/github/ascopes/jct/acceptancetests/dogfood/JctCompilationConfigurer.java
acceptance-tests/acceptance-tests-dogfood/src/test/java/io/github/ascopes/jct/acceptancetests/dogfood/JctDogfoodTest.java
acceptance-tests/acceptance-tests-dogfood/src/test/java/module-info.java
acceptance-tests/pom.xml
java-compiler-testing/pom.xml

Adds an acceptance test to "dogfood" compile JCT within itself.
This tests that the management of sources within JCT is close enough
to the regular javac file management implementation to enable compiling
a project with over 100 interlinked classes and transitive JPMS
dependencies into a RAM disk location.

Add tests to dogfood compiling JCT within JCT

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PackageContainerGroupUrlClassLoader.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PathWrappingContainerImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/AbstractCompilersProvider.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/AbstractCompilersProviderTest.java

If an error occurs using compiler configurers via the junit 
annotations because the module does not open itself to the 
JCT module for reflection, then show an error message showing
the snippet of code to add to module-info.java to fix this,
rather than propagating an internal reflection exception.

Add helpful error message if module errors encountered with junit support

---

acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-dogfood/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
java-compiler-testing/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/JctFileManagerTest.java
pom.xml

Add methods such as .getClassOutputGroup() for all StandardLocation members.

Add location helpers in JctFileManager

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/WorkspaceImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/WorkspaceTest.java

Closes #337 - adds new helper methods to the workspace API for accessing paths and locations within a workspace object within tests.

Add additional API method helpers to access workspace locations

---

java-compiler-testing/pom.xml
pom.xml

Adds a 'Fork me on GitHub ribbon to the JavaDocs', closes #340.

Add a GitHub ribbon to JavaDocs

---

acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-dogfood/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
java-compiler-testing/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompilerConfigurer.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompilers.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/JctCompilersTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/AbstractCompilersProviderTest.java
pom.xml
scripts/common.sh
scripts/prepare-test-outputs-for-merge.sh
scripts/update-versions.sh

Fixes a naming inconsistency in JctCompilers.createPlatformCompiler by deprecating this method in favour of a new method named JctCompilers.newPlatformCompiler.
Increments the current version to 0.2.0-SNAPSHOT

Rename JctCompilers.createPlatformCompiler to newPlatformCompiler

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/PackageContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompilationFactory.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactoryImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TeeWriter.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/PathFileObject.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/ExtraArgumentMatchers.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/CompilingSpecificClassesIntegrationTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JctCompilationFactoryImplTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/diagnostics/TeeWriterTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/PathFileObjectTest.java
java-compiler-testing/src/test/resources/integration/specificclasses/Fibonacci.java
java-compiler-testing/src/test/resources/integration/specificclasses/HelloWorld.java
java-compiler-testing/src/test/resources/integration/specificclasses/Sum.java
pom.xml

Fix explicit class handling.
- GH-354: Fail if no compilation units are found/filtered classes not found 
- Add new method: PathFileObject#getBinaryName
- JctCompilationFactoryImpl will now error if no initial compilation units
were found with a clearer error message.
- JctCompilationFactoryImpl will now error if any of the explicitly provided
class names are not found as compilation units.
- JctCompilationFactoryImpl will now error if the list of provided class
names is non-null but empty.
- Contributes to GH-294: Integration test compiling specific class names.
- API improvement that assists with GH-294: Allow call chaining on PackageContainerGroupAssert#allFilesExist (non-breaking API change).
- Fixes GH-356: Write tests for JctCompilationFactoryImpl  
- Add test pack for …

Fix explicit class handling

---

pom.xml

GH-369: Enforce exact Maven version is used for builds

---

README.md
acceptance-tests/acceptance-tests-dogfood/pom.xml
acceptance-tests/acceptance-tests-dogfood/src/test/java/module-info.java
java-compiler-testing/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JctExtension.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/Managed.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/WorkspaceImpl.java
java-compiler-testing/src/main/java/module-info.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/JctExtensionIntegrationTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/JctExtensionTest.java
java-compiler-testing/src/test/java/module-info.java

This enables declaring workspaces on a class level as fields and annotating them with the 'Managed' annotation to enable automatic creation and closure of workspaces as part of the JUnit workflow, leading to cleaner declarative test code.

Implement JctExtension JUnit extension.

---

acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-dogfood/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
java-compiler-testing/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/AbstractContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/ModuleContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/PackageContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/Container.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/PackageContainerGroup.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/AbstractPackageContainerGroup.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/JarContainerImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PathWrappingContainerImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/containers/impl/AbstractPackageContainerGroupTest.java
pom.xml

Fixes the file-exists assertion logic to prevent it getting confused when
archive file systems (like JARs) sit on the paths.
- Add new API methods for gathering all files across all containers.
- Add new API methods for retrieving the root directory of an archive-based container correctly.
- ...bump to v0.6.0 as this is a breaking API change unfortunately.
- Fix assertions for file discovery in package container groups to avoid confusion making
relative paths between various file systems.
- Make algorithm for matching files more concrete between different file system 
implementations (specifically Windows-like paths using backslashes for delimiters).

Fix path assertions across multiple file systems

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmPlatformClassPathConfigurer.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerFactoryImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/SpecialLocationUtils.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/JctFileManagerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmPlatformClassPathConfigurerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerFactoryImplTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/SpecialLocationsUtilsTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/WorkspaceTest.java

Platform class path functionality in the JVM was historically used before JPMS introduced system modules for the standard library. In lieu of that, the platform class path functionality is mostly deprecated, and has been reported to not work nicely in tests. Therefore, I am deprecating this with immediate effect for removal in v1.0.0.
Closes GH-396.

Deprecate all platform class path features for v1.0.0

---

.github/workflows/deploy.yml

This uses an environment for the main branch now to prevent allowing deployments on non-main branches (configured in GitHub  repo settings)

Only allow deployments to Maven central from the main branch

---

java-compiler-testing/pom.xml
pom.xml

- Update JaCoCo from 0.8.8 to 0.8.9
- Supports Java 20 bytecode
- Enable JaCoCo on Java 20 builds

Run JaCoCo on Java 20 builds

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/OutputContainerGroup.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/OutputContainerGroupImpl.java

Make output container groups only allow a single package

---

acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-checkerframework/src/test/groovy/io/github/ascopes/jct/acceptancetests/checkerframework/CheckerNullTest.groovy
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-error-prone/src/test/groovy/io/github/ascopes/jct/acceptancetests/errorprone/ErrorProneTest.groovy

Create a workaround to avoid failing tests when running multiple Maven modules at once. This can be removed once https://youtrack.jetbrains.com/issue/IDEA-317391 is fixed.

Add workaround for IDEA-317391 failing junit tests

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/PathStrategy.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/RamFileSystemProvider.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/JimfsFileSystemProviderImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/RamDirectoryImpl.java
java-compiler-testing/src/main/java/module-info.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/RamFileSystemProviderTest.java

RamFileSystemProvider realistically is not something we will ever expect the user to be making any use of, so can be safely deprecated and then removed on the v1.0.0 branch.

GH-419: Deprecate RamFileSystemProvider for removal.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/AbstractContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/ModuleContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/PackageContainerGroupAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/StringUtils.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/assertions/AbstractContainerGroupAssertTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/StringUtilsTest.java
java-compiler-testing/src/test/java/module-info.java

This refactors out some really annoying code I duplicated in a few places so that it is now reusable.
Need to just verify the rewrites don't impact path matching on Windows (hence the PR to verify first, as I am working on a Linux box).

Refactor out fuzzy string logic to an internal facility

---

.github/workflows/build.yml
README.md
acceptance-tests/acceptance-tests-lombok/src/test/groovy/io/github/ascopes/jct/acceptancetests/lombok/LombokIntegrationTest.groovy
pom.xml

Enable JDK 21 builds

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PackageContainerGroupUrlClassLoader.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/MemoryFileSystemProvider.java
pom.xml

Address previously breaking issues in memoryfilesystem regarding URL handling
now that a fix has been released for the library.
This means I can remove some additional logic in JCT that was previously
working around these issues.
Issues fixed:
- URL protocol handler now will filter by the requested URL scheme correctly.
- URLs for directories now have a trailing forward slash, so URLClassLoader
will not try to interpret it as a JAR and immediately ignore any files
in subdirectories.

Update memoyfilesystem with URL handling bugfixes

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/PathFileObjectAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/JarContainerImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PathWrappingContainerImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/PathFileObject.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/assertions/PathFileObjectAssertTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/PathFileObjectTest.java

- Deprecate PathFileObject#getFullPath for removal in v1.0.0 as it is not immediately clear 
what a "full path" means.
- Implement PathFileObject#getAbsolutePath to replace PathFileObject#getFullPath
- Implement PathFileObject assertion tests.

Implement path file object assertion tests

---

pom.xml

Enable the doclint JavaDoc linter as part of builds

Enable doclint for JavaDocs

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/Lazy.java

- Add missing Nullable annotation.
- Document Loom behaviour for synchronization.
- Use Lock rather than object mutexes to enable future loom support to function correctly.
- Mark class as final.

Tidy up Lazy.java

---

README.md
acceptance-tests/acceptance-tests-avaje-inject/pom.xml
acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
acceptance-tests/acceptance-tests-checkerframework/pom.xml
acceptance-tests/acceptance-tests-dagger/pom.xml
acceptance-tests/acceptance-tests-dogfood/pom.xml
acceptance-tests/acceptance-tests-error-prone/pom.xml
acceptance-tests/acceptance-tests-google-auto-factory/pom.xml
acceptance-tests/acceptance-tests-google-auto-service/pom.xml
acceptance-tests/acceptance-tests-google-auto-value/pom.xml
acceptance-tests/acceptance-tests-immutables/pom.xml
acceptance-tests/acceptance-tests-lombok/pom.xml
acceptance-tests/acceptance-tests-mapstruct/pom.xml
acceptance-tests/acceptance-tests-micronaut/pom.xml
acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml
acceptance-tests/acceptance-tests-serviceloader/pom.xml
acceptance-tests/acceptance-tests-spring/pom.xml
acceptance-tests/pom.xml
java-compiler-testing/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManagers.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerFactoryImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/UtilityClassTestTemplate.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/JctFileManagersTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerFactoryImplTest.java
pom.xml

Fixes GH-522.
Provides mechanisms for third-party compiler integrations to build instances of the default JctFileManager and JctFileManager factories.
- Implement a default implementation for `AbstractJctCompiler#getFileManagerFactory`, removing the `abstract` modifier.
- Implement a new class `JctFileManagers` which provides static methods for creating object instances of the default file manager implementations.
Non-breaking change, but a new feature, so bumping the minor version.

Implement default file manager creation hooks

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JavacJctCompilerImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/JctCompilerTest.java

Closes GH-496.
This sets the compiler to use the same language version as the current runtime feature version in the running JVM.

Implement JctCompiler.useRuntimeRelease()

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/PackageContainerGroup.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManagers.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/JctFileManagersTest.java

Plan for removal of dead method that doesn't make a lot of sense to keep.
Fix documentation issue I spotted at the same time.

Update JctFileManagers.java to deprecate newJctFileManager

---

pom.xml

Enable writing stacktraces to the console when errors occur in tests running within Surefire or Failsafe.

Print stacktraces to the console when errors occur in tests

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/LoggingFileManagerProxy.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/LoggingFileManagerProxyTest.java

Remove unneeded stack depth info from the LoggingFileManagerProxy

Remove stack depth functionality from LoggingFileManagerProxy

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManagers.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/JctFileManagersTest.java

Changes for the v2.0.0 release.
- Remove deprecated JctFileManagers#newJctFileManager.

v2.0.0 breaking changes

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerLoggingProxyConfigurer.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/LoggingFileManagerProxy.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerLoggingProxyConfigurerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/LoggingFileManagerProxyTest.java

Make LoggingFileManagerProxy an internal part of the JCT library for v2.0.0.
Users who need fine-grained control of the logging proxy can already do so via the JctCompiler interface, so there is no need to expose this component as part of the API.

Make LoggingFileManagerProxy internal

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JavacJctFlagBuilderImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JavacJctFlagBuilderImplTest.java

JDK 22 does not do this by default anymore, so we should add this to remain consistent between compiler versions.

Add -proc:all to compilation by default.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/CompilationMode.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JavacJctFlagBuilderImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JavacJctFlagBuilderImplTest.java

Fix the '-proc:full' flag to use the correct value. It currently uses `-proc:all` which isn't valid according to the OpenJDK Javac manpage.

Fix the '-proc:full' flag to use the correct value.

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ContainerGroupRepositoryImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmClassPathModuleConfigurer.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/ModuleDiscoverer.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/containers/impl/ContainerGroupRepositoryImplTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmClassPathModuleConfigurerTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/ModuleDiscovererTest.java

Fix an internal logic issue that caused warnings to appear for each build when an empty module path was provided (e.g. from surefire/failsafe target roots).
This also has the side effect of improving the accuracy of internal module-keeping logic slightly.

Improve accuracy of module discovery 

---

.github/workflows/build.yml

- Remove manual archive/unarchive now upload-artifact@v4 supports doing this implicitly without taking an extremely long time to do so.
- Remove concurrency limit as GitHub throttles this anyway.
- Remove manual codecov upload and use the action instead.
- Upload codecov directly from each runner rather than aggregating.

Simplify CI steps

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JavacJctFlagBuilderImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JavacJctFlagBuilderImplTest.java

This fixes some warnings when compiling sources with JDK22 while targeting older compilers.

Add -proc:full whenever we run under Java 22 or newer

---

java-compiler-testing/pom.xml
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/JctCompilationAssert.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/TypeAwareListAssert.java
pom.xml

This removes the need for FactoryBasedNavigableListAssert which is now deprecated for the purposes we were using it with.

Implement a new AbstractListAssert implementation that replaces FactoryBasedNavigableListAssert

---

java-compiler-testing/src/it/google-error-prone/pom.xml

A regression was created in the JDK 23 EA sources which breaks ErrorProne (see https://github.com/google/error-prone/issues/4415). 
Updating to 2.28.0 should fix this issue.

Fix Java 23 compatibility with Error Prone

---

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/OutputContainerGroupImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/FileUtils.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/DirectoryBuilder.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/FileBuilder.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/ManagedDirectory.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/AbstractManagedDirectory.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/DirectoryBuilderImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/FileBuilderImpl.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/MemoryFileSystemProvider.java
java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/WrappingDirectoryImpl.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/FileUtilsTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/impl/WrappingDirectoryImplTest.java

Add overloads for workspaces APIs to support list types.
All varargs methods now are accompanied by an overload that consumes a `java.util.List`.
The previous varargs overloads are now handled as default methods in most cases, so this is a breaking API change to be bundled with v4.0.0.
Fixes GH-721.

GH-721: Add overloads for workspaces APIs to support list types.

---

.github/workflows/build.yml

This disables CI builds for Java versions that are no longer supported by OpenJDK.
LTS builds will still be supported, but this reduces the number of builds we are performing that target obsolete platforms.

Remove EOL Java versions from build pipeline

---

.github/workflows/build-EA.yml
.github/workflows/build.yml

This enables CI builds for the latest Java versions supported by OpenJDK.

Add GA/EA versions to build pipeline

---

.github/workflows/build-EA.yml
.github/workflows/build.yml

Fix GA/EA action

---

java-compiler-testing/pom.xml
java-compiler-testing/src/it/avaje-http/pom.xml
java-compiler-testing/src/it/avaje-inject/pom.xml
java-compiler-testing/src/it/avaje-inject/src/test/java/io/github/ascopes/jct/acceptancetests/avajeinject/AvajeInjectTest.java
java-compiler-testing/src/it/avaje-inject/src/test/resources/code/module-info.java
java-compiler-testing/src/it/dagger/pom.xml
java-compiler-testing/src/it/google-auto-value/pom.xml
java-compiler-testing/src/it/google-error-prone/pom.xml
java-compiler-testing/src/it/google-error-prone/src/test/java/io/github/ascopes/jct/acceptancetests/errorprone/ErrorProneTest.java
java-compiler-testing/src/it/invoker-debug.properties
java-compiler-testing/src/it/lombok/pom.xml
java-compiler-testing/src/it/mapstruct/pom.xml
java-compiler-testing/src/it/micronaut/pom.xml
java-compiler-testing/src/it/spring/pom.xml

- Bump versions of components used in integration tests (other than avaje-jsonb, looks like this is not working correctly under a newer version, so that has been deferred).
- Add mechanism to allow attaching a remote debugger to tests via a Maven profile.

Update integration tests

---

pom.xml
scripts/close-nexus-repos.sh

See https://github.com/assertj/assertj/issues/2573\#issuecomment-2709477791

Update to AssertJ 4.0.0-M1

---

java-compiler-testing/src/it/lombok/pom.xml

Use edge version of Lombok to avoid JDK 24 failures until https://github.com/projectlombok/lombok/issues/3847#issuecomment-2762621662 is released as GA.

Use edge Lombok for JDK24 support

---

SECURITY.md
java-compiler-testing/pom.xml
java-compiler-testing/src/test/java/io/github/ascopes/jct/assertions/AbstractContainerGroupAssertTest.java
java-compiler-testing/src/test/java/io/github/ascopes/jct/utils/SpecialLocationsUtilsTest.java
pom.xml

Migrates from JUnit5 to JUnit6

GH-846: Migrate to Junit6
