.github/workflows/build.yml
=> Update codeql to v2

.github/workflows/main.yml, scripts/prepare-test-outputs-for-merge.sh
Add noclobber and nounset, and tidy up a bit.
=> Tidy up prepare-test-outputs-for-merge.sh

.github/workflows/main.yml, java-compiler-testing/pom.xml, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/IntegrationTest.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicLegacyCompilationIntegrationTest.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicModuleCompilationIntegrationTest.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicMultiModuleCompilationIntegrationTest.java, pom.xml
Thanks to @sohel-79 for helping with this.
---
This is currently on hold until I have time to work out why this is hanging.
=> (on hold) Implement mutation tests

.github/workflows/build.yml
=> Bulk collect reports into one archive after runs complete

pom.xml
- Remove --module-version as plugin does this automatically.
- Add parameter name data to compiled files.
- Output compilation warnings.
=> Update compiler config

.github/workflows/build.yml, java-compiler-testing/pom.xml, java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctCompilerImplTest.java, scripts/common.sh, scripts/prepare-test-outputs-for-merge.sh
=> Enable JDK 20 in builds

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/PathFileObject.java
Improve documentation, remove unneeded abstractions, and reorder members more appropriately.
=> Tidy up PathFileObject

.github/workflows/build.yml
=> Only run mutation tests on main branch

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmClassPathConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmClassPathModuleConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmModulePathConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmPlatformClassPathConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmSystemModulesConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerLoggingProxyConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerRequiredLocationsConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerWorkspaceConfigurer.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/package-info.java
=> Make changes to filemanager.config files

java-compiler-testing/src/main/java/module-info.java
=> Do not open modules to JUnit

java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TracingDiagnosticListener.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerFactoryImpl.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilersProvider.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/VisibleForTestingOnly.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerFactoryImplTest.java
- Adds tests for JctFileManagerFactoryImpl
- Adds a `@VisibleForTestingOnly` annotation internally.
=> JctFileManagerFactoryImpl tests

java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/ModuleDiscovererTest.java
Closes #293: Module discoverer tests
=> Module discoverer tests

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/deploy.yml
=> Freeze actions versions

java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/RamFileSystemProvider.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/JimfsFileSystemProviderImpl.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/RamFileSystemProviderTest.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/impl/JimfsFileSystemProviderImplTest.java
- RamFileSystemProvider tests.
- DefaultFileSystemProviderImpl is renamed to JimfsFileSystemProviderImpl.
- JimfsFileSystemProviderImpl tests.
=> Implement RamFileSystemProvider tests

acceptance-tests/acceptance-tests-avaje-inject/pom.xml, acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml, acceptance-tests/acceptance-tests-checkerframework/pom.xml, acceptance-tests/acceptance-tests-dagger/pom.xml, acceptance-tests/acceptance-tests-dogfood/pom.xml, acceptance-tests/acceptance-tests-error-prone/pom.xml, acceptance-tests/acceptance-tests-google-auto-factory/pom.xml, acceptance-tests/acceptance-tests-google-auto-service/pom.xml, acceptance-tests/acceptance-tests-google-auto-value/pom.xml, acceptance-tests/acceptance-tests-immutables/pom.xml, acceptance-tests/acceptance-tests-lombok/pom.xml, acceptance-tests/acceptance-tests-mapstruct/pom.xml, acceptance-tests/acceptance-tests-micronaut/pom.xml, acceptance-tests/acceptance-tests-serviceloader-jpms/pom.xml, acceptance-tests/acceptance-tests-serviceloader/pom.xml, acceptance-tests/acceptance-tests-spring/pom.xml, acceptance-tests/pom.xml, java-compiler-testing/pom.xml, java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/FileBuilder.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/FileBuilderImpl.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/JarFactoryImpl.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/workspaces/impl/JarFactoryImplTest.java, pom.xml
=> GH-370: Implement ability to create JARs from existing workspaces

pom.xml
=> GH-371: Fix license plugin warnings

.github/workflows/build.yml
=> Update report file detection in build.yml

acceptance-tests/acceptance-tests-avaje-jsonb/pom.xml
Trying out fixes as part of https://github.com/avaje/avaje-jsonb/issues/74
=> Update avaje-json to 1.4-RC

README.md
Fix some minor mistakes in the README.
=> Update README.md with example fixes

java-compiler-testing/src/main/java/io/github/ascopes/jct/repr/TraceDiagnosticRepresentation.java
Add missing nullability annotations to TraceDiagnosticRepresentation.
=> Nullability annotations in TraceDiagnosticRepresentation

acceptance-tests/acceptance-tests-error-prone/pom.xml
=> Update Error Prone to v2.20.0

.mvn/wrapper/maven-wrapper.properties
Update from Maven 3.9.2 to Maven 3.9.3
=> Build using Maven 3.9.3

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerConfigurerChain.java
Make the configurer chain synchronized to reduce the risk of confusing behaviour should test packs reuse this object between parallel tests.
Also adjusted logging and changed the internal queue implementation.
=> Synchronize JctFileManagerConfigurerChain.java

java-compiler-testing/src/main/java/io/github/ascopes/jct/repr/TraceDiagnosticRepresentation.java
Add missing comments as notes and tidy up code a bit.
=> Tidy TraceDiagnosticRepresentation.java

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerConfigurerChain.java
Improves support for project loom threads in the future by using locks rather than synchronization.
=> Use locks for JctFileManagerConfigurerChain.java

.github/workflows/deploy.yml, scripts/common.sh
Removed unneeded flags and added a dryrun option.
=> Tidy up deploy pipeline

java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JctExtension.java
Removal of some duplicated logic.
=> Tidy up JctExtension.java

java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/AbstractPackageContainerGroup.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/JarContainerImpl.java, java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/ModuleLocation.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/ModuleLocationTest.java
Finish adding missing JSpecify annotations
=> Update AbstractPackageContainerGroup.java with missing Nullability annotations

pom.xml
=> Update Mocktio from 5.6.0 to 5.7.0

.mvn/wrapper/maven-wrapper.properties
Update to Maven 3.9.6 for builds.
=> Build with Maven 3.9.6

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/security.yml, README.md
=> Update build.yml to build on Java 22

java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/PackageContainerGroupAssert.java
Improve error messages in PackageContainerGroupAssert for allFilesExist assertion.
The new format will now show all error messages as a list, as if it were done as a soft assertion.
=> Improve error messages in PackageContainerGroupAssert for allFilesExist assertion

.github/workflows/build.yml, README.md, scripts/prepare-test-outputs-for-merge.sh
Add support for building under JDK 23 early access.
=> JDK 23 early access support

java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerConfigurerChain.java
Thread safety was only partially supported in this class, with the configurers themselves lacking thread safety.
This logic has been removed entirely to prevent encouraging a false sense of safety.
=> Remove partial thread safety from JctFileManagerConfigurerChain.java

pom.xml
=> GH-664: update maven-gpg-plugin

.github/workflows/build.yml
=> Use codecov v4

.mvn/wrapper/maven-wrapper.properties
=> Use Maven 3.9.8 for builds

.github/workflows/deploy.yml, pom.xml
- Remove unneeded deployment profiles
- Skip second run of tests during deployments
=> Simplify deployment process

java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/AbstractCompilersProvider.java
This removes the hard requirement on the OpenTest4J module at runtime for users making use of JUnit5 functionality.
=> Remove hard references to OpenTest4J in AbstractCompilersProvider.java

README.md, java-compiler-testing/src/main/java/io/github/ascopes/jct/repr/TraceDiagnosticRepresentation.java, java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/repr/TraceDiagnosticRepresentationTest.java, java-compiler-testing/src/test/resources/io/github/ascopes/jct/tests/integration/compilation/BasicMultiModuleCompilationIntegrationTest/greeter/com/example/greeter/Greeter.java
Implements a simplified diagnostic representation that emits the code snippet to avoid overly spammy log outputs in tests.
Closes GH-720.
=> GH-720: Implement a simplified representation for diagnostics

.github/workflows/build.yml, README.md
=> Add Java 24 to builds

.github/workflows/build-EA.yml, java-compiler-testing/src/it/google-error-prone/selector.bsh, java-compiler-testing/src/it/lombok/selector.bsh, pom.xml
Set up builds to work with JDK EA releases.
(Thanks to @SentryMan for making me aware of this feature).
=> Configure builds for JDK EA

.github/workflows/deploy.yml, java-compiler-testing/pom.xml, pom.xml
Migrates to the new Maven Central release registry.
Fixes GH-805.
=> GH-805: Migrate to new Maven Central registry
